security:
  basic:
    enabled: true
  cas:
    enabled: true
    server:
      base-url: https://rnodev-login.hgicreate.com/cas
    service:
      resolution-mode: dynamic
    user:
      roles-attributes: roles
