security:
  basic:
    enabled: true
  cas:
    enabled: true
    server:
      base-url: https://cas.hgicreate.com:8443/cas
    service:
      resolution-mode: dynamic
    user:
      roles-attributes: roles
